#include<stdio.h>
#include<conio.h>
 void main()
  {
    int a,b,c,d,e,f,g,h,i,j,o;
    clrscr();

     printf("\n\t\t\t");
      textcolor(765);
      cprintf("MINI_LOGICAL COLLECTION");
      printf("\n\n");
      textcolor(76);
      cprintf("       Project Candidate  Name:               Project Duration:");
      printf("\n\t        Shridhar                           29-4-2020");
      printf("\n\t        Rahul                                TO");
      printf("\n\t        Manish                            3-5-2020");
       printf("\n\n\t\t\t\t");
       textcolor(RED);
      cprintf("INSTRUCTION");
       printf("\n\n\t");
       textcolor(YELLOW);
      cprintf("In this project are not copy for another code OR online codes.");
      printf("\n\t");
      cprintf("This project has been done logically and group discussion.");
      printf("\n\t");
      cprintf("   Step By Step Follow the Process Another you are Exit. ");
      printf("\n\n\t\t\t");
      textcolor(WHITE);
      cprintf("Project Names");
      printf("\n\n\t\t\t");
      textcolor(786);
      cprintf("1:_MCQ Questions");
      printf("\n\n\t\t\t");
      cprintf("2:-Car Parking");
      printf("\n\n\t\t\t");
      cprintf("3:-Age Calculater");
      printf("\n\n\t\t\t");
      cprintf("4:-Bank Simple Transition");
      printf("\n\n\t\t\t");
      textcolor(86);
      cprintf("Enter Your Choice :");
    scanf("%d",&o);
    switch(o)
      {
	case 1:
	  {



    int a,b,c,d,e,f,g,h,i,j,l,m,n,o,p,q,r,s,t,u,v;
    int k=0;
    clrscr();
	  textcolor(733);
	  printf("\n\n\t\t\t\t");
	  cprintf("M C Q");
	    textcolor(11);
		printf("\n\n\n");
	    cprintf("   Q.1 A ");
	   printf("\n\n\t");
	      textcolor(786);
    cprintf("Q.1 IC Chip used in computers are usually made of:");
       printf("\n\t");
	 textcolor(343);
       cprintf("1:-Lead");    printf("\n\t");
       cprintf("2:-Chromium");     printf("\n\t");
       cprintf("3:-Silicon");
       printf("\n\t");
       cprintf("4:-Gold");
       printf("\n\t");
       textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&a);
    switch(a)
    {
       case 1:
       {      textcolor(RED);
	 cprintf("                      Ans is wrong");
	 l=k+0;
       }
	  break;
	 case 2:
       {
	 textcolor(RED);
	 cprintf("                       Ans is wrong");
	 l=k+0;
       }
	 break;
	case 3:
       {
	 textcolor(9);
	 cprintf("                       right");
	 l=k+10;

       }
       break;
	case 4:
       {
	 textcolor(RED);
	 cprintf("                         Ans is wrong");
	 l=k+0;
	 break;
       }
       default:
       {
	  textcolor(765);
       cprintf("                           You enter wrong no.\n");
       }
  }

	printf("\n\t");
	textcolor(786);
	cprintf("One kilobyte is equal to:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-1000");    printf("\n\t");
       cprintf("2:-1024");     printf("\n\t");
       cprintf("3:-100");
       printf("\n\t");
       cprintf("4:-1034");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&b);
    switch(b)
    {
       case 1:
       {
	  textcolor(RED);
	 cprintf("                          Ans is wrong");
	 m=l+0;

       }
	  break;
	 case 2:
       {
	  textcolor(9);
	 cprintf("                          right");
	 m=l+10;
       }
	 break;
	case 3:
       {
	   textcolor(RED);
	 cprintf("                           Ans is wrong");
	 m=l+0;
       }
       break;
	case 4:
       {
	 textcolor(RED);
	 cprintf("                            Ans is wrong");
	 m=l+0;
	 break;
       }

       default:
       {
	 textcolor(765);
	cprintf("                               You enter wrong no.\n");
       }
  }


	printf("\n\t");
	textcolor(786);
	cprintf("Following is not Operating system:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-windows 98");    printf("\n\t");
       cprintf("2:-BSD Unix");     printf("\n\t");
       cprintf("3:-Red Hat Linux");
       printf("\n\t");
       cprintf("4:-Microsoft Office XP");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&c);
    switch(c)
    {
       case 1:
       {
	  textcolor(RED);
	 cprintf("                            Ans is wrong");
	 n=m+0;
       }
	  break;
	 case 2:
       {
	  textcolor(RED);
	 cprintf("                            Ans is wrong");
	 n=m+0;

       }
	 break;
	case 3:
       {
	  textcolor(RED);
	 cprintf("                            Ans is wrong");
	 n=m+0;
       }
       break;
	case 4:
       {
	  textcolor(9);
	 cprintf("                            right");
	 n=m+10;
	 break;
       }

       default:
       {
	 textcolor(765);
       cprintf("                               You enter wrong no.\n");
       }
  }


	printf("\n\t");
	textcolor(786);
	cprintf("Which Supercomputer is Develop by the indian Scientist:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-Super 301");    printf("\n\t");
       cprintf("2:-Compaq presario");     printf("\n\t");
       cprintf("3:-Param");
       printf("\n\t");
       cprintf("4:-mr.Jonson");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&d);
    switch(d)
    {
       case 1:
       {
	 textcolor(RED);
	 cprintf("                             Ans is wrong");
	 o=n+0;
       }
	  break;
	 case 2:
       {
	   textcolor(RED);
	 cprintf("                             Ans is wrong");
	  o=n+0;
       }
	 break;
	case 3:
       {
	  textcolor(9);
	 cprintf("                              right");
	 o=n+10;
       }
       break;
	case 4:
       {
	   textcolor(RED);
	 cprintf("                              Ans is wrong");
	 o=n+0;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                 You enter wrong no.\n");
       }

  }


	printf("\n\t");
	textcolor(786);
	cprintf("Name Of Microsoft Devloper");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-Sun Microsystem");    printf("\n\t");
       cprintf("2:-Nita Ambani ");     printf("\n\t");
       cprintf("3:-Bill Gates");
       printf("\n\t");
       cprintf("4:-J.K Husen");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&e);
    switch(e)
    {
       case 1:
       {
	  textcolor(RED);
	 cprintf("                               Ans is wrong");
	 p=o+0;
       }
	  break;
	 case 2:
       {
	  textcolor(RED);
	 cprintf("                               Ans is wrong");
	  p=o+0;
       }
	 break;
	case 3:
       {
	  textcolor(9);
	 cprintf("                                right");
	 p=o+10;
       }
       break;
	case 4:
       {
	  textcolor(RED);
	 cprintf("                                Ans is wrong");
	 p=o+0;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                  You enter wrong no.\n");
       }
    }


	printf("\n\t");
	textcolor(786);
	cprintf("Which Operating System use Millions of user:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-Ubantu");    printf("\n\t");
       cprintf("2:-Unix");     printf("\n\t");
       cprintf("3:-Linux");
       printf("\n\t");
       cprintf("4:-windows");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&f);
    switch(f)
    {
       case 1:
       {
	  textcolor(RED);
	 cprintf("                                 Ans is wrong");
	 q=p+0;
       }
	  break;
	 case 2:
       {
	  textcolor(RED);
	 cprintf("                                 Ans is wrong");
	  q=p+0;
       }
	 break;
	case 3:
       {
	  textcolor(RED);
	 cprintf("                                 Ans is wrong");
	  q=p+0;
       }
       break;
	case 4:
       {
	  textcolor(9);
	 cprintf("                                 right");
	 q=p+10;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                  You enter wrong no.\n");
       }
     }


	printf("\n\t");
	textcolor(786);
	cprintf("Which kind of Error can be pointed out by the compiler:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-Syntax error");    printf("\n\t");
       cprintf("2:-Logical Error");     printf("\n\t");
       cprintf("3:-Symantic error");
       printf("\n\t");
       cprintf("4:-internal error");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&g);
     switch(g)
    {
       case 1:
       {
	 textcolor(9);
	 cprintf("                                  right");
	 r=q+10;
       }
	  break;
	 case 2:
       {
	 textcolor(RED);
	 cprintf("                                  Ans is wrong");
	  r=q+0;
       }
	 break;
	case 3:
       {
	  textcolor(RED);
	 cprintf("                                   Ans is wrong");
	 r=q+0;

       }
       break;
	case 4:
       {
	 textcolor(RED);
	 cprintf("                                    Ans is wrong");
	 r=q+0;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                      You enter wrong no.\n");
       }

     }


	printf("\n\t");
	textcolor(786);
	cprintf("Which Data Type are use Declare of Number Vlaue:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-char");    printf("\n\t");
       cprintf("2:-int");     printf("\n\t");
       cprintf("3:-float");
       printf("\n\t");
       cprintf("4:-string");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&h);
    switch(h)
    {
       case 1:
       {
	  textcolor(RED);
	 cprintf("                                     Ans is wrong");
	 s=r+0;
       }
	  break;
	 case 2:
       {
	  textcolor(9);
	 cprintf("                                     right");
	 s=r+10;

       }
	 break;
	case 3:
       {
	   textcolor(RED);
	 cprintf("                                     Ans is wrong");
	   s=r+0;
       }
       break;
	case 4:
       {
	   textcolor(RED);
	 cprintf("                                     Ans is wrong");
	 s=r+0;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                        You enter wrong no.\n");
       }
     }


	printf("\n\t");
	textcolor(786);
	cprintf("which following C language Header file:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-#include<Max.h>");    printf("\n\t");
       cprintf("2:-#include<iostream.h>");     printf("\n\t");
       cprintf("3:-#include<stdio.h>");
       printf("\n\t");
       cprintf("4:-#include<out.h>");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&i);
    switch(i)
    {
       case 1:
       {
	   textcolor(RED);
	 cprintf("                                      Ans is wrong");
	 u=s+0;
       }
	  break;
	 case 2:
       {
	 textcolor(RED);
	 cprintf("                                      Ans is wrong");
	  u=s+0;
       }
	 break;
	case 3:
       {
	  textcolor(9);
	 cprintf("                                      right");
	 u=s+10;
       }
       break;
	case 4:
       {
	  textcolor(RED);
	 cprintf("                                      Ans is wrong");
	 u=s+0;
	 break;
       }
       default:
       {
       textcolor(765);
       cprintf("                                         You enter wrong no.\n");
       }
     }


	printf("\n\t");
	textcolor(786);
	cprintf("c language program run is:");
       printf("\n\t");
       textcolor(343);
       cprintf("1:-compiler");    printf("\n\t");
       cprintf("2:-interpreter");     printf("\n\t");
       cprintf("3:-mashine");
       printf("\n\t");
       cprintf("4:-runner");
       printf("\n\t");
	textcolor(YELLOW);
       cprintf("Ans:");
    scanf("%d",&j);
    switch(j)
    {
       case 1:
       {
	 textcolor(9);
	 cprintf("                                      right");
	 v=u+10;
       }
	  break;
	 case 2:
       {
	  textcolor(RED);
	 cprintf("                                      Ans is wrong");
	 v=u+0;
       }
	 break;
	case 3:
       {
	 textcolor(RED);
	 cprintf("                                       Ans is wrong");
	    v=u+0;
       }
       break;
	case 4:
       {
	  textcolor(RED);
	 cprintf("                                        Ans is wrong");
	 v=u+0;
	 break;
       }
       default:
       {
	 textcolor(765);
       cprintf("                                          You enter wrong no.\n");
       }
   }
    printf("\n");
    textcolor(134);
    cprintf("     your score is:- %d",v);



	      break;
	  }
	case 2:
	 {


    int a,b,c,d,e,f,g,x;

     clrscr();
	   printf("\n\n\t\t\t\t");
	   textcolor(134);
	   cprintf("Note");
	   printf("\n\t");
	   textcolor(WHITE);
	   cprintf(" Put follow information and get parking recips");
	   printf("\n");
	   printf("================================================================================\n");
	   textcolor(36);
	   cprintf(" Enter your name=");
	   scanf("%s",e);
	   cprintf(" Enter vahical number=");
	   scanf("%d",&d);  x=d+1243;
	   cprintf(" Vahical color=");
	   scanf("%s",c);
	   printf("\n\t\t");
	   textcolor(14);
	   cprintf("Your car Type");
	  printf("\n");
    printf("\t\t 1:-Bike  *100*\n");
    printf("\t\t 2:-Car *200*\n");
    printf("\t\t 3:-Bus  *300*\n\n");
       textcolor(786);
    cprintf(" Enter vahical type number=");
    scanf("%d",&a);
     if(a<=3)
      {
	 if(a==1)
	 {
	       textcolor(786);
	   cprintf(" Pay Ammount and get recipt=");
	   scanf("%d",&b);
	    if(b==100)
	     {
	       clrscr();
	       printf("\n\t\t");
	       textcolor(137);
	       cprintf(" ****** Thanks for pay ******");
	       printf("\n");
	       printf("\n================================================================================");
	       printf("\n\n\t\t\t");
	       textcolor(122);
	       cprintf(" Ricipt No. :%d",x);
	       printf("\n\n");
	       printf("\t\t\t");
	       textcolor(5);
	       cprintf(" Customer Name :%s",e);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Parking Amount :%d",b);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical Color :%s",c);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical No. :%d",d);
	       printf("\n");
	     }
	   else
	    {       printf("\n\n\t\t");
		textcolor(149);
	      cprintf("Sorry!! you does not pay sufficiant Ammount");
	    }
	 }
	 if(a==2)
	  {
		textcolor(786);
	     cprintf(" Pay the Ammount And get recips=");
	      scanf("%d",&b);

	      if(b==200)
	     {
		 clrscr();
	       printf("\n\t\t");
	       textcolor(137);
	       cprintf(" ****** Thanks for pay ******");
	       printf("\n");
	       printf("\n================================================================================");
	       printf("\n\n\t\t\t");
	       textcolor(122);
	       cprintf(" Ricipt No. :%d",x);
	       printf("\n\n");
	       printf("\t\t\t");
	       textcolor(5);
	       cprintf(" Customer Name :%s",e);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Parking Amount :%d",b);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical Color :%s",c);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical No. :%d",d);
	       printf("\n");

	     }
	   else
	    {
	      textcolor(149);
	      printf("\n\n\t\t");
	      cprintf("Sorry!! you does not pay sufficiant Ammount");
	    }
	  }
	   if(a==3)
	     {
		  textcolor(786);
		cprintf(" pay the Ammount And get Recips=");
		 scanf("%d",&b);

	      if(b==300)
	     {
	      clrscr();
	       printf("\n\t\t");
	       textcolor(137);
	       cprintf(" ****** Thanks for pay ******");
	       printf("\n");
	       printf("\n================================================================================");
	       printf("\n\n\t\t\t");
	       textcolor(122);
	       cprintf(" Ricipt No. :%d",x);
	       printf("\n\n");
	       printf("\t\t\t");
	       textcolor(5);
	       cprintf(" Customer Name :%s",e);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Parking Amount :%d",b);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical Color :%s",c);
	       printf("\n");
	       printf("\t\t\t");
	       cprintf(" Vahical No. :%d",d);
	       printf("\n");

	     }
	   else
	    {
	      textcolor(149);
	      printf("\n\n\t\t");
	      cprintf("Sorry!! you does not pay sufficiant Ammount");
	    }
	  }

       }

	 else
	  {         textcolor(149);
	      printf("\n\n\t\t");
	   cprintf("Sorry !!! You Enter Wrong choice\n");

	 }


	     break;
	 }
	case 3:
	 {




    int a,b,c,d,e,f,g,h,i,j,k,l,m,x,y;
    clrscr();
    printf("\n\n\t\t\t");
     textcolor(134);
     cprintf("Age Calculater");
     printf("\n\n\n");
     printf("\n\t\t");
	textcolor(YELLOW);
    cprintf("Enter your Current Day:-");
    scanf("%d",&a);
      printf("\t\t");
	textcolor(YELLOW);
     cprintf("Enter your Current Month:-");
     scanf("%d",&e);
       printf("\t\t");
	textcolor(YELLOW);
      cprintf("Enter your Current Year:-");
     scanf("%d",&i);
       printf("\t\t\t\t");
     textcolor(RED);
     cprintf("Wait");
       printf("\n\n\t\t");
	textcolor(9);
    cprintf("Enter your Birthday Day:-");
    scanf("%d",&b);
      printf("\t\t");
	textcolor(9);
     cprintf("Enter your Birthday Month:-");
    scanf("%d",&g);
    printf("\t\t");
    textcolor(9);
      cprintf("Enter your Birthday Year:-");
     scanf("%d",&j);
	 if(a==b&&e==g)
	   {
	     d=a-b;
	     h=e-g;
	     k=i-j;
	   }


	   if(a<b&&e==g)
	   {
	     c=a+30;
	     d=c-b;
	     f=e-1;
	     x=f+12;
	     h=x-g;
	     y=i-1;
	     k=y-j;
	   }


       if(a==b&&e>g)
	 {
	     d=a-b;
	     h=e-g;
	     k=i-j;

	}

     if(a<b)
      {
	 c=a+30;
	 d=c-b;    //date
	 f=e-1;    //subs 1  for months
	  if(e<g)
	   {
	     x=f+12;
	     h=x-g;
	     y=i-1;
	    k=y-j;
	   }
	 else
	 {
	   if(e>g)
	    {
	     h=e-g;
	     k=i-j;
	    }
	 }
      }  //correct code
       else
	{
	 if(a>b)
	  {
	    d=a-b;
	     if(e<g)
	     {
	      x=e+12;
	      h=x-g;
	      y=i-1;
	      k=y-j;
	     }
	      //correct code
	    else
	     {
	    // if(e>g)
	    //  {
		h=e-g;
		k=i-j;
	       }
	      }
	    }
		printf("\n\n");
	      textcolor(WHITE);
		cprintf("================================================================================");
		printf("\n");
	      printf("\n\n\t\t");

		textcolor(34);
	 cprintf("DAY:-%d",d);
	 printf("\t ");
	 textcolor(3);
	 cprintf("  MONTHS:-%d",h);
	  printf("\t ");
	 textcolor(122);
	  cprintf("YEAR:-%d",k);


	     break;
	 }
	case 4:
	 {



     clrscr();
     int a,b,c,d,e,f,g,h,i,v,u;
     int long k;
     char x,y,z,t;
     printf("\n\n\n");
     printf("\t\t\t\t");
     textcolor(147);
     cprintf("*Note*");
     printf("\n\n\t");
      textcolor(YELLOW);
      cprintf("Any user First create Account and get account no. and password.");
     printf("\n\t");
      cprintf("You follow step by step process.");
     printf("\n\n\n\t\t\t");
      textcolor(134);
     cprintf("  BANK   OF   RCC ");
     printf("\n\n\n\t\t\t");
      textcolor(1333);
     cprintf("1-Create Account");
     printf("\n\t\t\t");
     cprintf("2-logging Account");
      printf("\n\n\n\t\t\t");
      textcolor(4);
     cprintf("Enter your choice:-");
      scanf("%d",&i);
   switch(i) //main switch case of create account
    {
       case 1:
	 {        clrscr();
	   printf("\n\n\n\n\n\n\t\t");
	   textcolor(66);
	   cprintf("Enter your name:-");
	   scanf("%s",x);
	    printf("\n\t\t");
	   cprintf("Enter your Adhar number 4 digit:-");
	   scanf("%d",&a);
	   c=a+15;
	    printf("\n\t\t");
	   cprintf("Enter your password:-");
	   scanf("%d",&b);
	   v=b+0;
	   clrscr();
	    printf("\n\n\n\n\n\t\t");
	    textcolor(7866);
	   cprintf("Your Account is Succesfully Created !!!");
	    printf("\n\n\n\n\n\t\t\t");
	    textcolor(9);
	   cprintf("Your Account Number is:- %d",c);
	    printf("\n\t\t\t");
	   cprintf("Your Password is:-       %d",v);
	    printf("\n\n\n\t\t");
	    textcolor(YELLOW);
	   cprintf("Remember your Account No.And Password for next Process !!!");
	   printf("\n\n\n\n\n\t\t");
	   textcolor(635);
	   cprintf("Enter any number and Start Transition process:-");
	   scanf("%d",u);
	   if(u<=99)
	    {
	     printf("WELLCOME");
	    }
	  }

	case 2:   // logging section
	 {
	 clrscr();
	     printf("\n\n\t\t\t");
	     textcolor(637);
	    cprintf("WELLCOME LOGGING ACCOUNT");
	     printf("\n\n\t");
	     textcolor(638);
	   cprintf("\n\n\tEnter your Account Number:-");
	   scanf("%d",&d);
	    printf("\n\t");
	   cprintf("\n\tEnter your password:-");
	   scanf("%d",&e);
	       if(c==d)
		{
		  if(b==e)
		   {
		     printf("\n\n\t\t\t");
		     textcolor(786);
		    cprintf("Enter your Transition Type");
		      printf("\n\n\t\t\t");
		      textcolor(106);
		    cprintf("1:-Deposite");
		     printf("\n\t\t\t");
		    cprintf("2:-Widrawal");
		     printf("\n\t\t\t");
		    cprintf("3:-balance");
		     printf("\n\n\t\t\t");
		     textcolor(WHITE);
		    cprintf("Enter your Choice:-");
		    scanf("%d",&f);
		 switch (f)  //transition switch case inner
		  {
		   case 1:
		     {     clrscr();
		      printf("\n\n\t\t\t");
		      textcolor(33);
		      cprintf("Deposite Process");
		       printf("\n\n");
			textcolor(43);
		       cprintf("   Ammount Depositer Name:-");
			scanf("%s",t);
			 printf("\n");
		       cprintf("   Enter your Ammount:-");
		       scanf("%d",&g);
			printf("\n\n\n\t\t");
			textcolor(77);
		       cprintf("Your Ammount is Succesfully Added !!!");
		      }

		   case 2:
		     {
			 printf("\n\n\t\t\t");
			 textcolor(786);
		       cprintf("Widrawal Process");
			printf("\n\n");
			textcolor(43);
		      cprintf("  Enter Widrawal Ammount:-");
		      scanf("%d",&h);
			if(g>h)
			 {
			      printf("\n\t\t\t");
			      textcolor(134);
			     cprintf(" Collect your Money ");
			      printf("\n\n\t\t\t");
			       cprintf("!!!Thank You!!!");

			  }

		     }

		   case 3:
		     {
			printf("\n\n\t\t\t");
			textcolor(25);
		       cprintf(" Current Balance");
		       k=g-h;
			printf("\n\n\t");
			textcolor(YELLOW);
		       cprintf("Dear Customer Your Account Number %d is Balance is %d",c,k);
		     }
		  }  //switch close


		   }    // if close

		  else
		  {
		      printf("Your logging process faild");
		  }

	      }  //if close

	   }  //case 2 close
	   default:
	     {       textcolor(WHITE);
	     printf("\n\n\n\t\t\t");
	      //cprintf("Sorry You Choose Wrong Choice");
	      cprintf("=========!!!!!!==========");
	      }
     }  //switch case close



	    break;
	 }
	default:
	{
	    printf(" \n\n\n\t\t\tChoice is wrong !!!");

	}

    }
    getch();
}
